[package]
name = "rust-coding-test"
version = "0.1.0"
authors = ["Trevor Wilson <kmdreko@gmail.com>"]
edition = "2018"

[dependencies]
csv = "1.1.5"
serde = { version = "1.0.117", features = ["derive"] }
